import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ScrollNavigationMenu from "@/components/scroll-navigation-menu";
import FooterWrapper from "@/components/FooterWrapper";
import { THEME_STORAGE_KEY } from "@/store/theme-constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClerkProvider>
        <head>
          <script
            // Set theme class before paint to avoid flash.
            dangerouslySetInnerHTML={{
              __html: `(function(){try{var k=${JSON.stringify(
                THEME_STORAGE_KEY
              )};var t=localStorage.getItem(k);if(t==="light"){document.documentElement.classList.remove("dark");}else{document.documentElement.classList.add("dark");}}catch(e){document.documentElement.classList.add("dark");}})();`,
            }}
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh bg-background text-foreground`}
        >
          <ScrollNavigationMenu />
          {children}
          <FooterWrapper />
        </body>
      </ClerkProvider>
    </html>
  );
}
